// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrYx0ehmFAG-bjFVtlWMeV51tkdF7eTvs',
    appId: '1:899877293428:web:f742a46cec34bb9a3eb021',
    messagingSenderId: '899877293428',
    projectId: 'academyofccoding',
    authDomain: 'academyofccoding.firebaseapp.com',
    storageBucket: 'academyofccoding.firebasestorage.app',
    measurementId: 'G-R8YFZMT8Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4vkFqyTBxik4Ep4DWogkFbi0HFxYE7O0',
    appId: '1:899877293428:android:2de0888f21a13e753eb021',
    messagingSenderId: '899877293428',
    projectId: 'academyofccoding',
    storageBucket: 'academyofccoding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARWK9BFApZ8onz5jf9_FcDpZXUprgUw0Q',
    appId: '1:899877293428:ios:4c595bd8fde330c33eb021',
    messagingSenderId: '899877293428',
    projectId: 'academyofccoding',
    storageBucket: 'academyofccoding.firebasestorage.app',
    iosBundleId: 'com.example.academyOfCoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARWK9BFApZ8onz5jf9_FcDpZXUprgUw0Q',
    appId: '1:899877293428:ios:4c595bd8fde330c33eb021',
    messagingSenderId: '899877293428',
    projectId: 'academyofccoding',
    storageBucket: 'academyofccoding.firebasestorage.app',
    iosBundleId: 'com.example.academyOfCoding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrYx0ehmFAG-bjFVtlWMeV51tkdF7eTvs',
    appId: '1:899877293428:web:4f0cd20b80892f383eb021',
    messagingSenderId: '899877293428',
    projectId: 'academyofccoding',
    authDomain: 'academyofccoding.firebaseapp.com',
    storageBucket: 'academyofccoding.firebasestorage.app',
    measurementId: 'G-KYCLYXZKHS',
  );
}
